### PR TITLE
Add an option for file content as a string in an attachment Map

### PR DESCRIPTION
**Pull request by vysakh0**
Previously, we could send an attachment like this

```elixir
attachments: [%{path: "/tmp/image.png", filename: "img.png"}]
```

When one is generating a pdf or any files on the fly, one has to write
this as a temporary file in some place before sending it as an
attachment.

So with this, one could also send the file content like this

```elixir

def send_greetings(user, file_path) do
    file_content = File.read!(file_path)
    send_email to: user.email,
               from: @from,
               subject: "Happy b'day",
               html: "<strong>Cheers!</strong>",
              attachments: [%{content: file_content, filename: "img.png"}]
end
```

### CODE REVIEW

**Comment by chrismccord** [comment]
This looks great! Can you add a section to the `@moduledoc` about sending attachments in general, the options, and include this new feature in the examples?

**Comment by vysakh0** [comment]
Sure :+1:

**Comment by vysakh0** [comment]
I've added the `moduledoc`, can you please take a look? 
screenshot from 2015-11-29 20 51 05
screenshot from 2015-11-29 20 52 13


And this is embarrassing :flushed:  , I was squashing commits, and for some reason couldn't get these commits out from this pull request, I will make another pull request?

**Comment by vysakh0** [comment]
@chrismccord There wasn't an existing `@moduledoc`, so added few examples that were part of `README`, please review if it is okay.

**Comment by chrismccord** [comment]
<3 <3 <3

**Comment by vysakh0** [comment]
Wow, awesome, I was hesitant to give pull request at first (bit embarrassed about the code) thank you @optikfluffel chrismccord :+1: 

:heart: :green_heart: :blue_heart: :purple_heart: to the elixir community :+1:

**Pull request merged**
