### PR TITLE
Allow passing httpc opts

### PR DESCRIPTION
**Pull request by aerosol**
Hey, I needed finer control over request timeouts. Let me know please if that can be merged upstream. Thanks.

### CODE REVIEW

**Comment by aerosol** [comment]
@chrismccord ping, should I rebase the PR?

**Comment by chrismccord** [comment]
please rebase and I will merge

**Comment by aerosol** [comment]
@chrismccord done

**Comment by chrismccord** [comment]
Please doc the new config key and we are all set

**Comment by aerosol** [comment]
:+1: PR updated

**Comment by chrismccord** [comment]
<3 <3 <3

**Pull request merged**
